<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRepository extends \Doctrine\ORM\EntityRepository {

	public function getAll(){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
		->setParameter('isDelete',false)
        ->orderBy("e.id","DESC");
	}
	public function listAll(){
        return $this->getAll()
        ->select('e.id','e.email','e.picture','e.document','e.firstName');
	}
}
