<?php

namespace Apachecms\BackendBundle\Repository;
use Doctrine\ORM\Query\Expr;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
	public function createQuery($data){
		$em = $this->getEntityManager();
		$qb = $em->getRepository('ApachecmsBackendBundle:Country')->createQueryBuilder('e');
		$qb->select('e')
		->where('e.isDelete = 0')
		->orderBy("e.name","ASC");
		if($data){
			if(!empty($data["name"])) $qb->andWhere('e.name LIKE :name')->setParameter('name', '%'.$data["name"].'%');
			if(!empty($data["code"])) $qb->andWhere('e.code LIKE :code')->setParameter('code', '%'.$data["code"].'%');
		}
		return $qb->getQuery();
	}
	public function getAllActive(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('co')
            ->from('ApachecmsBackendBundle:Country','co')
            ->join('ApachecmsBackendBundle:Customer','cu',Expr\Join::WITH,$qb->expr()->eq('cu.country', 'co.id'))
            ->join('ApachecmsBackendBundle:Landing','l',Expr\Join::WITH,$qb->expr()->eq('cu.id', 'l.customer'))
            ->where('l.isPublished=1')
            ->andWhere('cu.isLocked =0')
            ->groupBy('cu.country')
        ;
        return $qb->getQuery()->getResult();
    }
}
