<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * CustomerTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerTransactionRepository extends \Doctrine\ORM\EntityRepository {

    public function getAll(){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
		->setParameter('isDelete',false)
        ->orderBy("e.id","DESC");
    }
    
    public function deleteAll($customer){
        $em = $this->getEntityManager();
        $query = "UPDATE customer_transaction t SET t.is_delete=1 WHERE t.customer='".$customer."'";
        $statement = $em->getConnection()->prepare($query);
        $result=$statement->execute();
    }

    public function listAll(){
        return $this->getAll()
        ->leftJoin('e.customer','c')
        ->andWhere('e.collectionStatus IN (:pending,:approved)')
        ->setParameter('pending','pending')
        ->setParameter('approved','approved')
        ->select(
            'e.id',
            'e.import',
            'e.paymentType',
            'e.collectionId',
            'e.collectionStatus',
            "CONCAT(c.firstName,' ',c.lastName) as c_name",
            "DATE_FORMAT(e.createdAt,'%d/%m/%Y %H:%i') as createdAt");
	}
}
