<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * DraftUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DraftUserRepository extends \Doctrine\ORM\EntityRepository
{
    
}
