<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * LandingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
        ->leftJoin('e.customer','c')
        ->leftJoin('e.business','b')
		->setParameter('isDelete',false)
        ->orderBy("e.createdAt","DESC");
    }
    
    public function findOneBySlug($slug,$usernameUrl=null){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
        ->andWhere('e.slug = :slug')
        ->andWhere('c.usernameUrl = :usernameUrl')
        ->andWhere('c.isLocked = :isLocked')
        ->leftJoin('e.customer','c')
		->setParameter('isDelete',false)
		->setParameter('slug',$slug)
		->setParameter('isLocked',false)
		->setParameter('usernameUrl',$usernameUrl)
        ->orderBy("e.id","DESC");
    }
    
	public function listAll(){
		return $this->getAll()
		->select('e.id','e.title','e.name','b.name as b_name','e.currentStep','e.slug','e.status','e.isReview',"CONCAT(c.firstName,' ',c.lastName) as c_name","DATE_FORMAT(e.createdAt,'%Y-%m-%d %H:%i') as createdAt");
	}

	public function getUniqueNotDeleted(array $parameters){
        return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
        ->setParameter('isDelete',false)
        ->andWhere('e.name= :name')
        ->setParameter('name',$parameters['name'])
        ->setMaxResults(1)->getQuery()->getResult();
    }
}
