<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * LandingQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandingQueryRepository extends \Doctrine\ORM\EntityRepository
{
}
