<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * LandingTestOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandingTestOptionRepository extends \Doctrine\ORM\EntityRepository
{
    
    
}
