<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * LandingContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandingContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll($customer=null){
		$qb=$this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
		->setParameter('isDelete',false)
        ->orderBy("e.id","DESC");
        if($customer)
            $qb->andWhere('e.customer =:customer')->setParameter('customer',$customer);
        return $qb;
    }
}
