<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * LandingLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandingLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
