<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
		->setParameter('isDelete',false)
        ->orderBy("e.id","DESC");
    }
    
    public function findAll(){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
		->setParameter('isDelete',false)
        ->orderBy("e.order","ASC")->getQuery()->getResult();
    }
    
	public function listAll(){
		return $this->getAll()
		->select('e.id','e.nameEs',"DATE_FORMAT(e.updatedAt,'%d/%m/%Y %H:%i') as updatedAt");
	}

	public function getUniqueNotDeleted(array $parameters){
        return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
        ->setParameter('isDelete',false)
        ->andWhere('e.code= :code')
        ->setParameter('code',$parameters['code'])
        ->setMaxResults(1)->getQuery()->getResult();
    }
}
