<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll(){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
		->setParameter('isDelete',false)
        ->orderBy("e.id","DESC");
    }
    
    public function findAll(){
		return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
		->setParameter('isDelete',false)
        ->orderBy("e.order","ASC")->getQuery()->getResult();
    }
    
	public function listAll(){
		return $this->getAll()
		->select('e.id','e.nameEs','e.price','e.order','e.percentDiscount','e.trialDays','e.maxBusiness','e.maxLanding',"e.updatedAt");
	}

	public function getUniqueNotDeleted(array $parameters){
        return $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.isDelete = :isDelete')
        ->setParameter('isDelete',false)
        ->andWhere('e.nameEs= :name')
        ->setParameter('name',$parameters['nameEs'])
        ->setMaxResults(1)->getQuery()->getResult();
    }
}
