<?php

namespace Apachecms\BackendBundle\Repository;

/**
 * StatMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatMessageRepository extends \Doctrine\ORM\EntityRepository
{
    
}   
