apachecms_frontend_pay:
    path:     /{plan}/{back}/{type}
    defaults:  
        { _controller: ApachecmsFrontendBundle:Pay:index, back: null, type: "12" }
    options:
        breadcrumb:
            label: Home
            parent_route: apachecms_frontend_dashboard


