# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Apachecms\BackendBundle\Entity\User: bcrypt
        Apachecms\BackendBundle\Entity\Customer: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:

        our_db_provider:
            entity:
                class: ApachecmsBackendBundle:User
                property: email
        customer_provider:
            entity:
                class: ApachecmsBackendBundle:Customer
                property: email
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            remember_me:
                secret:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ 
            anonymous: ~
            pattern:    /admin(.*)
            http_basic: ~
            provider: our_db_provider
            
            logout:
                path:   /admin/login/logout
                target: /admin

            form_login:
                default_target_path: /admin/
                always_use_default_target_path: true
                login_path: security_login
                check_path: security_login
        main:
            remember_me:
                secret:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ 
            anonymous: ~
            pattern:    /
            http_basic: ~
            provider: customer_provider
            
            logout:
                path:   /login/logout
                target: /
            context: application
            form_login:
                default_target_path: /dashboard
                always_use_default_target_path: true
                login_path: security_login_frontend
                check_path: security_login_frontend
    role_hierarchy:
        ROLE_ADMIN: ROLE_OPER
        ROLE_SUPER: ROLE_ADMIN

    access_control:
        - { path: ^/dashboard, roles: [ROLE_USER] }
        # - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/usuarios/*, roles: [ROLE_SUPER] }
        - { path: ^/admin/demos/delete/*, roles: [ROLE_ADMIN] }
        - { path: ^/admin/*, roles: [ROLE_OPER] }

        
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
