apachecms_api_business_add:
    path:     /add
    defaults: 
        _controller: ApachecmsApiBundle:Business:add
    methods: [POST]
apachecms_api_business_edit:
    path:     /add/{id}
    defaults: 
        _controller: ApachecmsApiBundle:Business:edit
    methods: [POST]
apachecms_api_business_getAll:
    path:     /getAll
    defaults: 
        _controller: ApachecmsApiBundle:Business:getAll
    methods: [GET]
apachecms_api_business_delete:
    path:     /delete/{id}
    defaults: {_controller: ApachecmsApiBundle:Business:delete}
    methods: [POST,DELETE]

